name: geo-env

dependencies:
  - python=3.9
  - pip=22.2.2
  - gdal=3.4.1
  - pip:
    - jupyter-server-proxy
    - rasterio --no-binary rasterio
    - rioxarray
    - geopandas
    - geemap
    - leafmap
    - xarray_leaflet
